config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: "pages#home"

  patch '/bookings/:id', to: 'bookings#update', as: 'update_booking'

  # vue de la recherche user
  resources :airports do
    resources :aircrafts
  end

  # vue owner de ses avions
  resources :users do
    resources :bookings
    resources :aircrafts do
      resources :bookings
    end
  end

  resources :aircrafts do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:edit] do
    patch :accept, on: :member
    patch :decline, on: :member
  end
  
  get 'search', to: 'airports#search'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get 'test', to: 'pages#test'

end

app/models/aircraft.rb
class Aircraft < ApplicationRecord
  belongs_to :airport
  belongs_to :owner, class_name: 'User'
  has_one_attached :photo
  has_many :bookings, dependent: :destroy
end

app/models/airport.rb
class Airport < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :aircraft
  has_one :airport, through: :aircraft

  validates :start_on, presence: true
  validates :end_on, presence: true

  # validates :start_on, uniqueness: true
  # validates :end_on, uniqueness: true

  validate :avaibility

  def days
    (start_on..end_on).to_a
  end

  private

  def avaibility
    return unless start_on && end_on

    dates_already_booked = aircraft.bookings.where.not(id: id).map(&:days).flatten.uniq
    return if (days & dates_already_booked).empty?



    errors.add(:start_on, "period not available")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  has_many :aircrafts, foreign_key: :owner_id
  has_many :bookings

  # validates :first_name, presence: true
  # validates :last_name, presence: true

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice("provider", "uid")
    user_params.merge! auth.info.slice("email", "first_name", "last_name")
    user_params[:facebook_picture_url] = auth.info.image
    puts "toto"
    puts auth.credentials
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end
end

app/controllers/aircrafts_controller.rb
class AircraftsController < ApplicationController

  before_action :set_aircrafts, only: [:show]

  def new
    @aircraft = Aircraft.new
    @airports = Airport.all
  end

  def index
    if current_user
      @aircrafts = Aircraft.where("owner_id = #{current_user.id}")
    else
      @aircrafts = []
    end

    @booking = Booking.new(aircraft: @aircraft)
    @dates = [5.days.from_now, 10.days.from_now]
  end

  def show
    # preparer un booking
    @booking = Booking.new(aircraft: @aircraft)
    # Je veux desactiver tous les jours qui se trouvent dans l'interval start_on end_on
    # @dates = [@start.days.from_now, @end.days.from_now]
    @disabled_dates = @aircraft.bookings.where(confirmed: true).map { |b| (b.start_on..b.end_on).to_a }.flatten.uniq
  end

  def create
    @aircraft = current_user.aircrafts.create!(aircraft_params)

    redirect_to user_aircrafts_path(current_user)
  end

  private

  def set_aircrafts
    @aircraft = Aircraft.find(params[:id])
  end

  def aircraft_params
    params.require(:aircraft).permit(:brand, :model, :daily_price, :owner_id, :airport_id, :photo)
  end
end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController
  def index
    @airports = Airport.all
  end

  def show
    @airport = Airport.find(params[:id])
    @aircrafts = Aircraft.where(airport_id: @airport.id)
  end

  def search
    @airports = Airport.where("name ILIKE ?", "%#{params[:query]}%")

    if  params[:query].present? && @airports.exists?
      render :search, layout: false
    else
      render plain: ''
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


  private

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name])
  end

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end
end


# class ApplicationController < ActionController::Base
#   before_action :configure_permitted_parameters, if: :devise_controller?

#   protected

#   def configure_permitted_parameters
#     devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
#   end
# end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[accept decline]
  before_action :set_aircraft, only: %i[create]
  def create
    @booking = Booking.new(booking_params)
    @booking.end_on = end_on
    @booking.user = current_user
    @booking.aircraft = @aircraft

    # if Booking.where(start_on: @booking.start_on, end_on: @booking.end_on).exists?
    #   Flash.now[:alert] = "Cet avion est déjà réservé"
    # else
    if @booking.save
      redirect_to root_path, status: :see_other
    else
      @error_booking = @booking.errors.full_messages
      render 'aircrafts/show'
    end
  end

  def new
    @booking = Booking.new
  end

  def index
    @bookings = Booking.where("user_id = #{params[:user_id]}")
    # if b.aircraft.owner_id == params(user_id) then display ?
    # @reservations = Booking.where("aircraft_id = #{Aircraft.where("owner_id = #{params[:user_id]}").ids}")
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def accept
    @booking.update!(confirmed: true)
    redirect_to user_aircrafts_path(current_user)
  end

  def decline
    @booking.update!(confirmed: false)
    redirect_to user_aircrafts_path(current_user)
  end

  private

  def end_on
    booking_params[:start_on].split(' ').last
  end

  def set_aircraft
    @aircraft = Aircraft.find(params[:aircraft_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_on, :end_on, :confirmed)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @aircrafts = Aircraft.all
  end

  def test
    if params[:query].present?
      ap "coucou"
      @aircrafts = Aircraft.where(airport: params[:query])
    else
      @movies = Movie.all
    end
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def facebook
      user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

      if user.persisted?
        sign_in_and_redirect user, event: :authentication
        set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
      else
        session['devise.facebook_data'] = request.env['omniauth.auth']
        redirect_to new_user_registration_url
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # def number_to_currency(number, options = {})
  #   delegate_number_helper_method(:number_to_currency, number, options)
  # end
end

app/views/aircrafts/_form.html.erb
<body class="splash">
  <div class="container">
    <%= @error_booking %>
    <%= simple_form_for [@aircraft, @booking] do |f| %>
    <%# <input type="text" id="calandar" data-action="focus->show#check" data-date-disable="<%= @dates.to_json %>
    <%= f.text_field :start_on,
        data: {
          controller: "flatpickr",
          flatpickr_min_date: Time.zone.now, #disables past dates
          flatpickr_mode: 'range',
          flatpickr_disable: @disabled_dates.to_json,
        } %>
      <%= f.submit 'Réserver', class: "btn btn-primary btn-lg" %>
    <% end %>
  </div>
</body>

app/views/aircrafts/index.html.erb
<body class="splash">
  <div class="container" id="crad-show">
    <div style="display: flex; flex-direction: row; justify-content: space-between">
      <h1 id="title-my-aircraft">Mes avions</h1>
      <p><%= link_to "Ajouter un avion", current_user.present? ? new_user_aircraft_path(current_user) : new_user_registration_path, class: "btn btn-primary" %></p>
    </div>
    <div class="data-container" id="space-under-elements">
      <% if @aircrafts.any? %>
        <% @aircrafts.each do |a| %>
          <div class="element">
          <% if a.photo.attached? %>
            <%= cl_image_tag a.photo.key, id: "image", class: "zoom-in-out-box", alt: "aicraft" %>
          <% end %>
            <div class="text-content">
              <div class="text">
                  <h1>CONSTRUCTEUR : <%= a.brand %></h1>
                  <h2>Cet avion est proposé par <strong><%= a.owner.first_name %> </strong></h2>
                  <p class="card-text">Série : <%= a.model %></p>

                  <p class="card-text"><small class="text-muted">Price : <%= number_to_currency(a.daily_price, unit: "€", delimiter: " ", precision: 0, format: "%n %u") %> </small></p>
              </div>
              <div class="confirmed">
                <h4>Réservations confirmées et à confirmer :</h4>
                <% a.bookings.order("confirmed desc").each do |b| %>
                  <div class="card-booking-owner">
                    <div class="card-booking-owner-infos">
                        <h3> Client : <strong><%= b.user.first_name %></strong> </h3>
                        <p>Location <strong><%= a.model %> </strong> du <%= b.start_on.strftime("%d/%m/%Y") %> au <%= b.end_on.strftime("%d/%m/%Y") %> </p>
                        <p>
                          <% if b.confirmed == nil %>
                            <p style="color: orange">En attente</p>
                          <% elsif b.confirmed == true %>
                            <p style="color: blue">Validée</p>
                          <% else %>
                            <p style="color: red">Refusée</p>
                          <% end %>
                        </p>
                        <% if b.confirmed == nil %>
                        <%= link_to "Valider", accept_booking_path(b), data: {turbo_method: :patch, turbo_confirm: "Are you sure?"}, style: "background-color:green; color:aliceblue; padding:8px;" %>
                        <%= link_to "Refuser", decline_booking_path(b), data: {turbo_method: :patch, turbo_confirm: "Are you sure?"}, style: "background-color:red; color:aliceblue; padding:8px;" %>
                        <% end %>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>

      <% else %>
        <p>
          <strong>Il n'y a pas d'avions pour cet utilisateur</strong>
        </p>
      <% end %>
    </div>
  </div>
</body>

app/views/aircrafts/new.html.erb
<body class="splash">
  <div class="container">
    <h2 class="mt-4 mb-4" style="text-align: center">AJOUTER UN AVION À LA LOCATION</h2>
    <div class="new-form">
      <%= simple_form_for @aircraft do |a| %>
        <%= a.input :brand,
                    label: "Marque",
                    collection: ["Airbus", "Boeing"] %>
        <%= a.input :model,
                    label: "Modèle",
                    collection: ["A320", "A318", "777", "787"] %>
        <%= a.input :airport_id,
                    label: "Aéroport",
                    collection: @airports %>
        <%= a.input :daily_price,
                    label: "Prix" %>
        <%= a.input :photo, as: :file %>
        <%= a.submit class: "btn btn-ghost mt-4" %>
      <% end %>
    </div>
  </div>
</body>

app/views/aircrafts/show.html.erb
<div class="container" id="crad-show">
<div class="data-container">
  <%# <img id="image" class="zoom-in-out-box" src="https://images.pexels.com/photos/3811676/pexels-photo-3811676.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" alt="aircraft-leggs"> %>
  <%= cl_image_tag @aircraft.photo.key, alt: "aircraft-leggs", id: "image", class: "zoom-in-out-box" %>
  </div>
  <div class="text-content">
    <div class="text">
      <h1>CONSTRUCTEUR : <%= @aircraft.brand %></h1>
      <h2>Cet avion est proposé par <strong><%= @aircraft.owner.first_name %> </strong></h2>
      <p class="card-text">Série : <%= @aircraft.model %></p>
      <p class="card-text"><small class="text-muted">Price : <%= @aircraft.daily_price %> $</small></p>
        <%= render 'aircrafts/form' %>
    </div>
  </div>
</div>

app/views/airports/index.html.erb
<div class="container">
  <h1>Aéroports</h1>
  <div>
    <li>
      <% @airports.each do |a| %>
        <ul><%= link_to a.name, airport_path(a) %></ul>
      <% end %>
    </li>
  </div>
</div>

app/views/airports/search.html.erb
<div class="search-list">
  <ul>
    <% @airports.each do |airport| %>
       <li><%= link_to airport.name, airport_path(airport) %></li>
    <% end %>
  </ul>
</div>

app/views/airports/show.html.erb
<div class="container">
  <h1>Avions disponibles à <%= @airport.name %></h1>
  <% @aircrafts.each do |a| %>
    <%= link_to aircraft_path(a), :action => 'go' do %>
        <div class="card-trip mt-4 mb-4">
          <% if a.photo.attached? %>
              <%= cl_image_tag a.photo.key, class: "card-img-top", alt: "aicraft" %>
          <% end %>
          <%# <img src="https://images.unsplash.com/photo-1598281343081-0f36311fe207?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2940&q=80" > %>
          <div class="card-trip-infos">
            <div>
              <h2><%= a.brand%> | <%= a.model  %></h2>
              <p><%= a.airport.name%> <%= a.airport.city_code %>,   De : <%=  a.owner.first_name  %></p>
            </div>
            <h2 class="card-trip-pricing"><%= a.daily_price%>$</h2>
            <img class="card-trip-user avatar-bordered" src="https://cdn-icons-png.flaticon.com/512/4036/4036835.png">
          </div>
        </div>
    <% end %>
  <% end %>
</div>

app/views/bookings/index.html.erb
<body class="splash">
  <div class="container" id="crad-show">
    <div style="display: flex; flex-direction: row; justify-content: space-between">
      <h1 id="title-my-aircraft">Mes réservations</h1>
      <p><%= link_to "Ajouter un avion", current_user.present? ? new_user_aircraft_path(current_user) : new_user_registration_path, class: "btn btn-primary" %></p>
    </div>
    <div class="data-container" id="space-under-elements">
     <% if @bookings.exists? %>
        <% @bookings.each do |b| %>
          <div class="element">
            <% if b.aircraft.photo.attached?  %>
              <%= cl_image_tag b.aircraft.photo.key, id: "image", class: "zoom-in-out-box", alt: "aicraft" %>
            <% end %>

            <div class="text-content">
              <div class="text">
                  <h1>CONSTRUCTEUR : <%= b.aircraft.brand %></h1>
                  <h2>Cet avion est proposé par <strong><%= b.aircraft.owner.first_name %></strong></h2>
                  <p class="card-text">Série : <%= b.aircraft.model %></p>
                  <p class="card-text">Période : <%= b.start_on.strftime("%d/%m/%Y") %> | <%= b.end_on.strftime("%d/%m/%Y") %></p>

                  <p class="card-text"><small class="text-muted">Price : <%= number_to_currency(b.aircraft.daily_price, unit: "€", delimiter: " ", precision: 0, format: "%n %u") %> </small>$</p>
              </div>
              <div class="confirmed">
                <p>Statut de la réservation :
                  <% if b.confirmed == nil %>
                    <strong style="color:orange">En attente de validation</strong>
                  <% elsif b.confirmed == true %>
                    <strong style="color:green">Validée</strong>
                  <% elsif b.confirmed == false %>
                    <strong style="color:red">Refusée</strong>
                  <% end %>
                </p>
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <p>
          <strong>Il n'y a pas de réservation pour cet utilisateur</strong>
        </p>
      <% end %>
    </div>
  </div>
</body>

app/views/bookings/new.html.erb
<h1>New booking for <%= @aircraft.brand %> <%= @aircraft.model %> at <%= @aircraft.airport.name %></h1>
<%= simple_form_for [@aircraft, @booking] do |b| %>
  <%= b.input :start_on, as: :date %>
  <%= b.input :end_on, as: :date %>
   <%= b.text_field :start_on,
    data: {
      controller: "flatpickr",
      flatpickr_date_format: "Y-m-d",
      flatpickr_min_date: Time.zone.now
    } %>
  <%= b.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAirbnplane</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <p class="alert"><%= alert %></p>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <%= render "shared/footer"%>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">

 <h1 class="hhome" style="margin-bottom: 30px">Find your plane</h1>


  <div class="search-bar" data-controller="search">
    <div class="col-12" >
      <input type="text" class="form-control" placeholder="Find airport"
             data-search-target="input"
             data-action="input->search#update"
             style="padding: 10px;text-align: center">
      <div data-search-target="list"></div>
    </div>
  </div>


  <div style="margin-top: 100px">
    <% @aircrafts.each do |aircraft| %>
      <%= link_to aircraft_path(aircraft), :action => 'go' do %>
        <div class="card-trip mt-4 mb-4">
          <% if aircraft.photo.attached? %>
            <%= cl_image_tag aircraft.photo.key, id: "home-img", alt: "aicraft" %>
          <% end %>
          <div class="card-trip-infos">
            <div>
              <h2><%= aircraft.brand %> | <%= aircraft.model  %></h2>
              <p><%= aircraft.airport.name%> <%= aircraft.airport.city_code %>,   De : <%=  aircraft.owner.first_name  %></p>
            </div>
            <h2 class="card-trip-pricing"><%= aircraft.daily_price%>$</h2>
            <img class="card-trip-user avatar-bordered" src="https://cdn-icons-png.flaticon.com/512/4036/4036835.png">
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

</div>

app/views/pages/test.html.erb
<h1>Ma page de test</h1>


<input type="text" id="aa" data-date-disable="<%= @dates.to_json %>">
<input type="text" id="bb" data-date-disable="<%= @dates.to_json %>">

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/adromel/rails-airbnplane" target="_blank"><i class="fab fa-github"></i></a>
    <a href="https://www.instagram.com/dassaultaviation/?hl=fr" target="_blank"><i class="fab fa-instagram"></i></a>
    <a href="https://twitter.com/dgac" target="_blank"><i class="fab fa-twitter"></i></a>
    <a href="https://www.linkedin.com/showcase/lewagonparis/?originalSubdomain=fr" target="_blank"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="copyright">
    <p><span>© AirBnPlane</span></p>
  </div>
  <div class="footer-copyright">
    This app was made with <i class="fas fa-heart"></i> at Le Wagon Lyon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">


  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <i class="fa-solid fa-plane-departure fa-2x"></i>
      <h1 style="color: white">AirBnPlane</h1>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <% if user_signed_in? %>
            <li class="nav-item active">
              <%= link_to "Accueil", root_path, class: "nav-link"%>
            </li>
            <li class="nav-item active">
              <%= link_to "Mes réservations", user_bookings_path(current_user), class: "nav-link"%>
            </li>
            <li class="nav-item active">
              <%= link_to "Mes avions", user_aircrafts_path(current_user), class: "nav-link"%>
              <% current_user.aircrafts.each do |a| %>
                <% a.bookings.each do |b| %>
                  <% if b.present? && !b.confirmed %>
                    <span class="position-absolute top-0 l-75 start-100 translate-middle p-2 bg-danger border border-light rounded-circle"></span>
                  <% end %>
                <% end %>
              <% end %>
            </li>
            <li class="nav-item dropdown">
            <i class="fa-solid fa-earth-europe fa-3x" class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <p class="dropdown-item dropdown-user"><%= current_user&.email %></p>
              <hr class="dropdown-divider">
              <%# <%= link_to "Notifications", "#", class: "dropdown-item" %>
              <%= link_to "Mes réservations", user_bookings_path(current_user), class: "dropdown-item" %>
              <%= link_to "Créer une annonce", new_user_aircraft_path(current_user), class: "dropdown-item" %>
              <%# <%= link_to "Compte", "#", class: "dropdown-item" %>
              <%= link_to "Déconnexion", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Connexion", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>

  </div>
</div>